checked in the patches for nginx 1.5.3; also applied the unix_socket_accept_over_read patch the nginx cores older than 1.5.3.

diff --git a/util/mirror-tarballs b/util/mirror-tarballs
--- a/util/mirror-tarballs
+++ b/util/mirror-tarballs
@@ -109,13 +109,19 @@ echo "$info_txt applying the location_if_inherits_proxy patch for nginx"
 patch -p1 < $root/patches/nginx-$main_ver-location_if_inherits_proxy.patch || exit 1
 echo
 
-echo "$info_txt applying the upstream_truncation patch for nginx"
-patch -p1 < $root/patches/nginx-$main_ver-upstream_truncation.patch || exit 1
-echo
+answer=`$root/util/ver-ge "$main_ver" 1.5.3`
+if [ "$answer" = "N" ]; then
+    echo "$info_txt applying the upstream_truncation patch for nginx"
+    patch -p1 < $root/patches/nginx-$main_ver-upstream_truncation.patch || exit 1
+    echo
+fi
 
-echo "$info_txt applying the channel-uninit-params patch for nginx"
-patch -p1 < $root/patches/nginx-$main_ver-channel-uninit-params.patch || exit 1
-echo
+answer=`$root/util/ver-ge "$main_ver" 1.5.3`
+if [ "$answer" = "N" ]; then
+    echo "$info_txt applying the channel-uninit-params patch for nginx"
+    patch -p1 < $root/patches/nginx-$main_ver-channel-uninit-params.patch || exit 1
+    echo
+fi
 
 echo "$info_txt applying the dtrace patch for nginx"
 patch -p1 < $root/patches/nginx-$main_ver-dtrace.patch || exit 1
@@ -153,14 +159,24 @@ if [ "$answer" = "N" ]; then
     echo
 fi
 
-echo "$info_txt applying patches/nginx-$main_ver-invalid_referer_hash.patch for nginx"
-patch -p1 < $root/patches/nginx-$main_ver-invalid_referer_hash.patch || exit 1
-echo
+answer=`$root/util/ver-ge "$main_ver" 1.5.3`
+if [ "$answer" = "N" ]; then
+    echo "$info_txt applying patches/nginx-$main_ver-invalid_referer_hash.patch for nginx"
+    patch -p1 < $root/patches/nginx-$main_ver-invalid_referer_hash.patch || exit 1
+    echo
+fi
 
 answer=`$root/util/ver-ge "$main_ver" 1.4.1`
 if [ "$answer" = "Y" ]; then
     echo "$info_txt applying patches/nginx-$main_ver-gcc-maybe-uninitialized-warning.patch for nginx"
     patch -p1 < $root/patches/nginx-$main_ver-gcc-maybe-uninitialized-warning.patch
+    echo
+fi
+
+answer=`$root/util/ver-ge "$main_ver" 1.5.3`
+if [ "$answer" = "N" ]; then
+    echo "$info_txt applying the unix_socket_accept_over_read patch for lua $ver"
+    patch -p1 < $root/patches/nginx-$ver-unix_socket_accept_over_read.patch || exit 1
     echo
 fi
 
