bugfix: setting $args might not make ngx_proxy (and others) honour the change. applied the setting_args_invalidates_uri patch to fix this issue. thanks rvsw for the report.

diff --git a/util/mirror-tarballs b/util/mirror-tarballs
--- a/util/mirror-tarballs
+++ b/util/mirror-tarballs
@@ -225,6 +225,10 @@ echo "$info_txt applying the resolve-names-with-a-trailing-dot patch for nginx $
 patch -p1 < $root/patches/nginx-$ver-resolve-names-with-a-trailing-dot.patch || exit 1
 echo
 
+echo "$info_txt applying the setting_args_invalidates_uri patch for nginx $ver"
+patch -p1 < $root/patches/nginx-$ver-setting_args_invalidates_uri.patch || exit 1
+echo
+
 rm -f *.patch || exit 1
 
 cd .. || exit 1
