feature: applied the invalid_referer_hash patch to the nginx core to make the $invalid_referer variable accessible in embedded dynamic languages like Perl and Lua. thanks Fry-kun for requesting this.

diff --git a/util/mirror-tarballs b/util/mirror-tarballs
--- a/util/mirror-tarballs
+++ b/util/mirror-tarballs
@@ -150,6 +150,10 @@ echo "$info_txt applying patches/nginx-$main_ver-cve-2013-2070.patch for nginx"
 patch -p0 < $root/patches/nginx-$main_ver-cve-2013-2070.patch || exit 1
 echo
 
+echo "$info_txt applying patches/nginx-$main_ver-invalid_referer_hash.patch for nginx"
+patch -p1 < $root/patches/nginx-$main_ver-invalid_referer_hash.patch || exit 1
+echo
+
 rm -f *.patch || exit 1
 
 cd .. || exit 1
