feature: applied the larger_max_error_str patch to the nginx core to allow error log messages up to 4096 bytes.

diff --git a/util/mirror-tarballs b/util/mirror-tarballs
--- a/util/mirror-tarballs
+++ b/util/mirror-tarballs
@@ -210,6 +210,10 @@ if [ "$answer" = "N" ]; then
     echo
 fi
 
+echo "$info_txt applying the larger_max_error_str patch for nginx $ver"
+patch -p1 < $root/patches/nginx-$ver-larger_max_error_str.patch || exit 1
+echo
+
 rm -f *.patch || exit 1
 
 cd .. || exit 1
