bugfix: applied a patch to the nginx core to fix a memory invalid read regression introduced in nginx 1.7.5+'s resolver.

diff --git a/util/mirror-tarballs b/util/mirror-tarballs
--- a/util/mirror-tarballs
+++ b/util/mirror-tarballs
@@ -266,6 +266,10 @@ if [ "$answer" = "N" ]; then
     echo
 fi
 
+echo "$info_txt applying the resolver_del_event_invalid_read patch for nginx"
+patch -p1 < $root/patches/nginx-$main_ver-resolver_del_event_invalid_read.patch || exit 1
+echo
+
 rm -f *.patch || exit 1
 
 cd .. || exit 1
